[package]
name = "piClock"
version = "0.1.0"
authors = ["Dave Crowder <dave@crowder.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
chrono = "0.4"